# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = [
    "nanobind>=2.10",
    "scikit-build-core>=0.10",
    "setuptools",
]
build-backend = "scikit_build_core.setuptools.build_meta"

[project]
name = "allo"
version = "0.5"
dependencies = [
    "rich",
    "numpy",
]
requires-python = ">=3.12"
authors = [
    {name = "Allo Authors"}
]
description = "Allo: Accelerator Design and Programming Language"
readme = {file = "README.md", content-type = "text/markdown"}
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["compiler", "hls", "fpga", "accelerator"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: System :: Hardware",
    "Operating System :: OS Independent"
]

[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.version = ">=3.20"
ninja.version = ">=1.10"
cmake.build-type = "Release"
cmake.args = [
    "-S mlir"
]
build-dir = "build"

[tool.setuptools]
packages = ["allo"]
