# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Typing stubs for elementwise math operators."""

from typing import Any

__all__ = [
    "exp",
    "exp2",
    "log",
    "log2",
    "abs",
    "pow",
    "sqrt",
    "rsqrt",
    "sin",
    "cos",
    "tan",
    "floor",
    "ceil",
    "erf",
    "fma",
]

def exp(value: Any, acc: Any = ...) -> Any: ...
def exp2(exp: Any, acc: Any = ...) -> Any: ...
def log(value: Any, acc: Any = ...) -> Any: ...
def log2(value: Any, acc: Any = ...) -> Any: ...
def abs(value: Any, acc: Any = ...) -> Any: ...
def pow(base: Any, exp: Any, acc: Any = ...) -> Any: ...
def sqrt(value: Any, acc: Any = ...) -> Any: ...
def rsqrt(value: Any, acc: Any = ...) -> Any: ...
def sin(value: Any, acc: Any = ...) -> Any: ...
def cos(value: Any, acc: Any = ...) -> Any: ...
def tan(value: Any, acc: Any = ...) -> Any: ...
def sinh(value: Any, acc: Any = ...) -> Any: ...
def cosh(value: Any, acc: Any = ...) -> Any: ...
def tanh(value: Any, acc: Any = ...) -> Any: ...
def floor(value: Any, acc: Any = ...) -> Any: ...
def ceil(value: Any, acc: Any = ...) -> Any: ...
def erf(value: Any, acc: Any = ...) -> Any: ...
def fma(a: Any, b: Any, c: Any) -> Any: ...
