# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import builtins
from typing import Any, Dict, Iterator, List, Optional, Sequence, TypeAlias

from .._C.liballo import ir

_ConstLike: TypeAlias = constexpr | int | float | bool
_TensorLike: TypeAlias = tensor | constexpr

class base_type:
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def gen_proxy_value(
        self, handles: Sequence[ir.Value], cursor: int
    ) -> tuple[base_value, int]: ...
    def append_ir_types(self, builder: ir.OpBuilder, out: List[ir.Type]) -> None: ...
    def mangle(self) -> str: ...
    @staticmethod
    def __call__(*args: Any, **kwargs: Any) -> tensor: ...

class base_value:
    type: base_type
    def append_ir_values(self, out: List[ir.Value]) -> None: ...

class constexpr_type(base_type):
    value: Any
    def __init__(self, value: Any): ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def mangle(self) -> str: ...
    def gen_proxy_value(
        self, handles: List[ir.Value], cursor: int
    ) -> tuple[base_value, int]: ...
    def append_ir_types(self, builder: ir.OpBuilder, out: List[ir.Type]) -> None: ...

class constexpr(base_value):
    value: Any
    type: constexpr_type
    def __init__(self, value: Any): ...
    def __repr__(self) -> str: ...
    def append_ir_values(self, out: List[ir.Value]) -> None: ...
    def __bool__(self) -> bool: ...
    def __index__(self) -> int: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> constexpr: ...
    def __le__(self, other: Any) -> constexpr: ...
    def __gt__(self, other: Any) -> constexpr: ...
    def __ge__(self, other: Any) -> constexpr: ...
    def __eq__(self, other: object) -> constexpr: ...
    def __ne__(self, other: object) -> constexpr: ...

def _unwrap_if_constexpr(o: Any) -> Any: ...
def _is_allo_non_scalar_tensor(o: Any) -> bool: ...
def _is_scalar_tensor(o: Any) -> bool: ...
def _is_array_of_scalar_tensor(o: Any) -> bool: ...
def _is_allo_stream(o: Any) -> bool: ...

class scalar_type(base_type):
    name: str
    primitive_width: int
    def __init__(self, name: str, width: int): ...
    def __eq__(self, other: object) -> bool: ...
    @property
    def scalar(self) -> scalar_type: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def append_ir_types(self, builder: ir.OpBuilder, out: List[ir.Type]) -> None: ...
    def gen_proxy_value(
        self, handles: List[ir.Value], cursor: int
    ) -> tuple[base_value, int]: ...
    def to_ir(self, builder: ir.OpBuilder) -> ir.Type: ...
    def is_int_signless(self) -> bool: ...
    def is_int(self) -> bool: ...
    def is_intn(self, n: int) -> bool: ...
    def is_uint(self) -> bool: ...
    def is_uintn(self, n: int) -> bool: ...
    def is_float(self) -> bool: ...
    def is_fp16(self) -> bool: ...
    def is_bf16(self) -> bool: ...
    def is_fp32(self) -> bool: ...
    def is_fp64(self) -> bool: ...
    def is_index(self) -> bool: ...

type_placeholder: scalar_type

class APInt(scalar_type):
    signed: bool
    def __init__(self, bitwidth: int, signed: bool = True): ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def to_ir(self, builder: ir.OpBuilder) -> ir.Type: ...
    def mangle(self) -> str: ...
    @staticmethod
    def __call__(value: int, *, ann: Optional[str] = None) -> tensor: ...

int1: APInt
int2: APInt
int3: APInt
int4: APInt
int5: APInt
int6: APInt
int7: APInt
int8: APInt
int9: APInt
int10: APInt
int11: APInt
int12: APInt
int13: APInt
int14: APInt
int15: APInt
int16: APInt
int32: APInt
int64: APInt
uint1: APInt
uint2: APInt
uint3: APInt
uint4: APInt
uint5: APInt
uint6: APInt
uint7: APInt
uint8: APInt
uint9: APInt
uint10: APInt
uint11: APInt
uint12: APInt
uint13: APInt
uint14: APInt
uint15: APInt
uint16: APInt
uint32: APInt
uint64: APInt

class APFloat(scalar_type):
    exp_width: int
    mantissa_width: int
    def __init__(self, exp_width: int, mantissa_width: int): ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def to_ir(self, builder: ir.OpBuilder) -> ir.Type: ...
    def mangle(self) -> str: ...
    @staticmethod
    def __call__(value: float | int, *, ann: Optional[str] = None) -> tensor: ...

fp16: APFloat
fp32: APFloat
fp64: APFloat
bf16: APFloat

class index_type(scalar_type):
    def __init__(self, width: int = 32): ...
    def to_ir(self, builder: ir.OpBuilder) -> ir.Type: ...
    def mangle(self) -> str: ...

index: index_type

def _unwrap_shape(shape: Sequence[Any]) -> List[Any]: ...

class Array(base_type):
    base_ty: scalar_type
    shape: Sequence[int]
    numel: int
    name: str
    def __init__(self, base_ty: scalar_type, shape: Sequence[Any]): ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def to_ir(self, builder: ir.OpBuilder) -> ir.Type: ...
    def append_ir_types(self, builder: ir.OpBuilder, out: List[ir.Type]) -> None: ...
    def gen_proxy_value(
        self, handles: List[ir.Value], cursor: int
    ) -> tuple[base_value, int]: ...
    def mangle(self) -> str: ...
    @staticmethod
    def __call__(
        base_ty: scalar_type,
        shape: Sequence[int],
        init: Optional[tensor | constexpr] = None,
        ann: Optional[str] = None,
    ) -> tensor: ...

array: Array

class slice_type(base_type):
    name: str
    def __init__(self): ...

class tuple_type(base_type):
    types: Sequence[base_type]
    fields: Sequence[str] | None
    def __init__(
        self, types: Sequence[base_type], fields: Optional[Sequence[str]] = None
    ): ...
    @property
    def name(self) -> str: ...
    def __str__(self) -> str: ...
    def __iter__(self) -> Iterator[base_type]: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, index: int) -> base_type: ...
    def append_ir_types(self, builder: ir.OpBuilder, out: List[ir.Type]) -> None: ...
    def gen_proxy_value(
        self, handles: List[ir.Value], cursor: int
    ) -> tuple[base_value, int]: ...
    def mangle(self) -> str: ...

class Channel(base_type):
    last_indices: List[List[tensor]]
    name: str
    data_ty: scalar_type | Array
    capacity: int
    shape: Sequence[int]
    dshape: Sequence[int]
    def __init__(
        self,
        name: str,
        data_ty: scalar_type | Array,
        shape: Sequence[int],
        capacity: int = 2,
    ): ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def append_ir_types(self, builder: ir.OpBuilder, out: List[ir.Type]) -> None: ...
    def mangle(self) -> str: ...
    @staticmethod
    def __call__(
        name: str,
        data_ty: scalar_type | Array,
        capacity: int = 2,
        shape: builtins.tuple[constexpr, ...] | None = None,
    ) -> tensor: ...

channel: Channel

def _type_for_tuple_values(
    values: Sequence[Any], fields: Optional[Sequence[str]] = None
) -> tuple_type: ...
def _normalize_tuple(t: Any) -> tuple: ...

class tuple(base_value):
    values: List[Any]
    type: tuple_type
    is_constexpr: bool
    def __init__(
        self,
        values: Sequence[Any],
        type: Optional[tuple_type] = None,
        is_constexpr: bool = False,
    ): ...
    def __getitem__(self, index: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __add__(self, other: Any) -> tuple: ...
    def __mul__(self, other: constexpr) -> tuple: ...
    def __eq__(self, other: object) -> constexpr: ...
    def __str__(self) -> str: ...
    def __iter__(self) -> Iterator[Any]: ...
    def append_ir_values(self, out: List[ir.Value]) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...

class slice:
    start: Any
    stop: Any
    step: Any
    type: slice_type
    def __init__(self, start: Any, stop: Any, step: Any): ...

def check_bit_width(value: Any, shift_value: Any) -> None: ...

class tensor(base_value):
    handle: ir.Value
    shape: Sequence[int]
    numel: int
    type: base_type
    dtype: scalar_type
    def __init__(self, handle: ir.Value, type: base_type): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def append_ir_values(self, out: List[ir.Value]) -> None: ...
    def __hash__(self) -> int: ...
    def __add__(self, other: _TensorLike) -> tensor: ...
    def __radd__(self, other: _TensorLike) -> tensor: ...
    def __sub__(self, other: _TensorLike) -> tensor: ...
    def __rsub__(self, other: _TensorLike) -> tensor: ...
    def __mul__(self, other: _TensorLike) -> tensor: ...
    def __rmul__(self, other: _TensorLike) -> tensor: ...
    def __truediv__(self, other: _TensorLike) -> tensor: ...
    def __rtruediv__(self, other: _TensorLike) -> tensor: ...
    def __floordiv__(self, other: _TensorLike) -> tensor: ...
    def __rfloordiv__(self, other: _TensorLike) -> tensor: ...
    def __mod__(self, other: _TensorLike) -> tensor: ...
    def __rmod__(self, other: _TensorLike) -> tensor: ...
    def __pow__(self, other: _TensorLike) -> tensor: ...
    def __rpow__(self, other: _TensorLike) -> tensor: ...
    def __neg__(self) -> tensor: ...
    def __pos__(self) -> tensor: ...
    def __invert__(self) -> tensor: ...
    def __and__(self, other: _TensorLike) -> tensor: ...
    def __rand__(self, other: _TensorLike) -> tensor: ...
    def __or__(self, other: _TensorLike) -> tensor: ...
    def __ror__(self, other: _TensorLike) -> tensor: ...
    def __xor__(self, other: _TensorLike) -> tensor: ...
    def __rxor__(self, other: _TensorLike) -> tensor: ...
    def __lshift__(self, other: _TensorLike) -> tensor: ...
    def __rlshift__(self, other: _TensorLike) -> tensor: ...
    def __rshift__(self, other: _TensorLike) -> tensor: ...
    def __rrshift__(self, other: _TensorLike) -> tensor: ...
    def __lt__(self, other: _TensorLike) -> tensor: ...
    def __le__(self, other: _TensorLike) -> tensor: ...
    def __gt__(self, other: _TensorLike) -> tensor: ...
    def __ge__(self, other: _TensorLike) -> tensor: ...
    def __eq__(self, other: object) -> tensor: ...
    def __ne__(self, other: object) -> tensor: ...
    def __getitem__(self, key: Any) -> tensor: ...
    def __setitem__(self, key: Any, value: Any) -> tensor | None: ...
    def acquire(self, size: int | constexpr = 1) -> tensor: ...
    def release(self, *buffers: tensor) -> None: ...
    def put(self, value: tensor | constexpr, blocking=False) -> None: ...
    def get(self, blocking=False) -> tensor: ...

class range:
    name: str
    start: Any
    stop: Any
    step: Any
    def __init__(
        self,
        start: Any,
        stop: Any = None,
        step: Any = None,
        *,
        unroll: Any = None,
        pipeline: Any = None,
        name: constexpr = ...,
    ): ...
    def __iter__(self) -> range: ...
    def __next__(self) -> int: ...

class grid:
    name: str
    starts: List[Any]
    stops: List[Any]
    steps: List[Any]
    def __init__(self, *ranges: tuple, name: constexpr = ...): ...
    def __iter__(self) -> grid: ...
    def __next__(self) -> tuple[int, ...]: ...

torch_types_to_core_types_map: Dict[str, scalar_type]
