from typing import Sequence
from . import ir

class NamedSequenceOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder,
        name: str,
        root_ty: ir.Type,
        res_types: Sequence[ir.Type],
    ) -> NamedSequenceOp: ...
    @property
    def entry_block(self) -> ir.Block: ...
    def get_arg_at(self, index: int) -> ir.BlockArgument: ...

class OperationType(ir.Type):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def get(context: ir.Context, name: str) -> OperationType: ...

class AnyOpType(ir.Type):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def get(context: ir.Context) -> AnyOpType: ...

class YieldOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, operands: Sequence[ir.Value]) -> YieldOp: ...

class ApplyCSEOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, target: ir.Value) -> ApplyCSEOp: ...

class ApplyDCEOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, target: ir.Value) -> ApplyDCEOp: ...

class ApplyCanonicalizationOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder) -> ApplyCanonicalizationOp: ...

class ApplyPatternsOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, target: ir.Value) -> ApplyPatternsOp: ...
    @property
    def body(self) -> ir.Block: ...

class ApplyLICMOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, target: ir.Value) -> ApplyLICMOp: ...

class MatchOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder,
        target: ir.Value,
        res_ty: ir.Type,
        op_names: Sequence[str],
        op_attrs: ir.DictionaryAttr | None = None,
    ) -> ir.Value: ...

class LoopUnrollOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, target: ir.Value, factor: int
    ) -> LoopUnrollOp: ...

class MergeHandlesOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, handles: Sequence[ir.Value], deduplicate: bool = True
    ) -> MergeHandlesOp: ...

class SplitHandleOp(ir.OpState):
    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, handle: ir.Value, num_splits: int
    ) -> SplitHandleOp: ...

def apply_transforms(
    payload: ir.Operation, transform_root: ir.Operation, transform_module: ir.ModuleOp
) -> tuple[bool, str]: ...
