#include "act/Support/SemanticMatching.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/Debug.h"

#define DEBUG_TYPE "semantic-matching"

using namespace mlir;
using namespace mlir::act;

using llvm::dbgs;

static bool isLayoutOp(Operation *op) {
  return isa<tensor::ExtractSliceOp, tensor::InsertSliceOp,
             tensor::ExpandShapeOp, tensor::CollapseShapeOp,
             linalg::TransposeOp>(op);
}

static bool isPlaceholderOp(Operation *op) {
  if (isa<tensor::EmptyOp, arith::ConstantOp>(op))
    return true;
  if (auto fillOp = dyn_cast<linalg::FillOp>(op)) {
    return llvm::all_of(fillOp.getInputs(), [](Value v) {
      return v.getDefiningOp<arith::ConstantOp>() || isa<BlockArgument>(v);
    });
  }
  return false;
}

static bool isPrimitiveSemanticOp(Operation *op) {
  return isa<linalg::GenericOp, linalg::SoftmaxOp, linalg::MapOp,
             linalg::ReduceOp, linalg::ContractOp>(op) ||
         // TODO:
         isa<linalg::AddOp, linalg::MatmulOp>(op);
}

static DenseSet<Operation *> findPreTransforms(Block &b) {
  DenseSet<Operation *> preTransforms;
  bool changed = true;
  while (changed) {
    changed = false;
    for (Operation &op : b) {
      if (preTransforms.contains(&op))
        continue;
      if (!isLayoutOp(&op) && !isPlaceholderOp(&op))
        continue;
      // check if all operands are either block arguments
      // or generated by valid placeholders.
      if (llvm::all_of(op.getOperands(), [&](Value v) {
            Operation *defOp = v.getDefiningOp();
            if (!defOp)
              return true;
            // can propagate through layout ops
            return preTransforms.contains(defOp) || isPlaceholderOp(defOp);
          })) {
        preTransforms.insert(&op);
        changed = true;
      }
    }
  }
  return preTransforms;
}

static bool hasStaticEntries(ArrayRef<int64_t> values) {
  return llvm::none_of(
      values, [](int64_t value) { return ShapedType::isDynamic(value); });
}

static FailureOr<StaticSlice> getFullStaticSlice(Value value) {
  auto type = dyn_cast<RankedTensorType>(value.getType());
  if (!type)
    return emitError(value.getLoc()) << "expected ranked tensor value";
  if (!type.hasStaticShape())
    return emitError(value.getLoc())
           << "dynamic tensor shape is unsupported in semantic matching "
              "layout provenance";

  StaticSlice slice;
  for (int64_t size : type.getShape()) {
    slice.offsets.push_back(0);
    slice.sizes.push_back(size);
    slice.strides.push_back(1);
  }
  return slice;
}

template <typename SliceOp>
static FailureOr<StaticSlice> getStaticSlice(SliceOp op) {
  auto offsets = op.getStaticOffsets();
  auto sizes = op.getStaticSizes();
  auto strides = op.getStaticStrides();
  if (!hasStaticEntries(offsets) || !hasStaticEntries(sizes) ||
      !hasStaticEntries(strides))
    return op.emitError()
           << "dynamic slice is unsupported in semantic matching layout "
              "provenance";

  StaticSlice slice;
  llvm::append_range(slice.offsets, offsets);
  llvm::append_range(slice.sizes, sizes);
  llvm::append_range(slice.strides, strides);
  return slice;
}

static bool hasUnitStrides(const StaticSlice &slice) {
  return llvm::all_of(slice.strides,
                      [](int64_t stride) { return stride == 1; });
}

static bool sameRank(const StaticSlice &lhs, const StaticSlice &rhs) {
  return lhs.offsets.size() == rhs.offsets.size() &&
         lhs.sizes.size() == rhs.sizes.size() &&
         lhs.strides.size() == rhs.strides.size();
}

static int64_t getSliceEnd(const StaticSlice &slice, unsigned dim) {
  assert(slice.strides[dim] == 1 && "expected unit-stride slice");
  return slice.offsets[dim] + slice.sizes[dim];
}

static FailureOr<StaticSlice> composeExtractSlice(const StaticSlice &outer,
                                                  const StaticSlice &inner,
                                                  Operation *op) {
  if (!sameRank(outer, inner))
    return op->emitError() << "rank-reducing slice provenance is unsupported";

  StaticSlice result;
  for (unsigned dim = 0; dim < outer.offsets.size(); ++dim) {
    result.offsets.push_back(outer.offsets[dim] +
                             inner.offsets[dim] * outer.strides[dim]);
    result.sizes.push_back(inner.sizes[dim]);
    result.strides.push_back(outer.strides[dim] * inner.strides[dim]);
  }
  return result;
}

static FailureOr<std::optional<StaticSlice>>
intersectSlices(const StaticSlice &lhs, const StaticSlice &rhs, Operation *op) {
  if (!sameRank(lhs, rhs))
    return op->emitError() << "slice ranks do not match";
  if (!hasUnitStrides(lhs) || !hasUnitStrides(rhs))
    return op->emitError() << "non-unit-stride slice overlap is unsupported";

  StaticSlice result;
  for (unsigned dim = 0; dim < lhs.offsets.size(); ++dim) {
    int64_t begin = std::max(lhs.offsets[dim], rhs.offsets[dim]);
    int64_t end = std::min(getSliceEnd(lhs, dim), getSliceEnd(rhs, dim));
    if (begin >= end)
      return std::optional<StaticSlice>();
    result.offsets.push_back(begin);
    result.sizes.push_back(end - begin);
    result.strides.push_back(1);
  }
  return std::optional<StaticSlice>(std::move(result));
}

static bool slicesEqual(const StaticSlice &lhs, const StaticSlice &rhs) {
  return lhs.offsets == rhs.offsets && lhs.sizes == rhs.sizes &&
         lhs.strides == rhs.strides;
}

static StaticSlice mapIntoInsertedSource(const StaticSlice &slice,
                                         const StaticSlice &inserted) {
  assert(sameRank(slice, inserted) && "expected same-rank slices");
  assert(hasUnitStrides(slice) && hasUnitStrides(inserted) &&
         "expected unit-stride slices");
  StaticSlice mapped = slice;
  for (unsigned dim = 0; dim < mapped.offsets.size(); ++dim)
    mapped.offsets[dim] -= inserted.offsets[dim];
  return mapped;
}

static FailureOr<StaticSlice>
mapTransposeOutputToInputSlice(const StaticSlice &slice,
                               ArrayRef<int64_t> permutation, Operation *op) {
  if (slice.offsets.size() != permutation.size())
    return op->emitError() << "transpose slice rank does not match";

  StaticSlice mapped;
  mapped.offsets.resize(permutation.size());
  mapped.sizes.resize(permutation.size());
  mapped.strides.resize(permutation.size());
  for (auto [outDim, inDim] : llvm::enumerate(permutation)) {
    if (inDim < 0 || static_cast<size_t>(inDim) >= permutation.size())
      return op->emitError() << "transpose permutation index out of range";
    mapped.offsets[inDim] = slice.offsets[outDim];
    mapped.sizes[inDim] = slice.sizes[outDim];
    mapped.strides[inDim] = slice.strides[outDim];
  }
  return mapped;
}

static StaticSlice mapWantedSubsliceToTarget(const StaticSlice &subslice,
                                             const StaticSlice &wanted,
                                             const StaticSlice &target) {
  assert(sameRank(subslice, wanted) && sameRank(wanted, target) &&
         "expected same-rank slices");
  assert(hasUnitStrides(wanted) && hasUnitStrides(target) &&
         "expected unit-stride target slice mapping");

  StaticSlice mapped;
  for (unsigned dim = 0; dim < subslice.offsets.size(); ++dim) {
    assert(subslice.offsets[dim] >= wanted.offsets[dim] &&
           "subslice should be contained in wanted slice");
    mapped.offsets.push_back(target.offsets[dim] + subslice.offsets[dim] -
                             wanted.offsets[dim]);
    mapped.sizes.push_back(subslice.sizes[dim]);
    mapped.strides.push_back(subslice.strides[dim]);
  }
  return mapped;
}

static SmallVector<StaticSlice, 4> subtractSlice(const StaticSlice &slice,
                                                 const StaticSlice &remove) {
  assert(sameRank(slice, remove) && "expected same-rank slices");
  assert(hasUnitStrides(slice) && hasUnitStrides(remove) &&
         "expected unit-stride slices");

  SmallVector<StaticSlice, 4> pieces;
  StaticSlice remaining = slice;
  for (unsigned dim = 0; dim < slice.offsets.size(); ++dim) {
    int64_t removeBegin = remove.offsets[dim];
    int64_t removeEnd = getSliceEnd(remove, dim);

    if (remaining.offsets[dim] < removeBegin) {
      StaticSlice piece = remaining;
      piece.sizes[dim] = removeBegin - remaining.offsets[dim];
      pieces.push_back(std::move(piece));

      remaining.sizes[dim] -= removeBegin - remaining.offsets[dim];
      remaining.offsets[dim] = removeBegin;
    }

    int64_t remainingEnd = getSliceEnd(remaining, dim);
    if (removeEnd < remainingEnd) {
      StaticSlice piece = remaining;
      piece.offsets[dim] = removeEnd;
      piece.sizes[dim] = remainingEnd - removeEnd;
      pieces.push_back(std::move(piece));

      remaining.sizes[dim] = removeEnd - remaining.offsets[dim];
    }
  }
  assert(slicesEqual(remaining, remove) &&
         "slice subtraction should leave the removed region");
  return pieces;
}

static FailureOr<SmallVector<LayoutChain, 4>>
resolveLayoutChains(Value value, std::optional<StaticSlice> wantedSlice,
                    DenseSet<Operation *> &semanticOps,
                    SmallVector<Operation *, 4> layoutOps = {},
                    std::optional<StaticSlice> targetSlice = std::nullopt) {
  Operation *defOp = value.getDefiningOp();
  if (!defOp || semanticOps.contains(defOp) || isPlaceholderOp(defOp)) {
    LayoutChain chain;
    chain.source = value;
    chain.slice = std::move(wantedSlice);
    chain.targetSlice = std::move(targetSlice);
    chain.layoutOps = std::move(layoutOps);
    std::reverse(chain.layoutOps.begin(), chain.layoutOps.end());
    return SmallVector<LayoutChain, 4>{std::move(chain)};
  }

  if (auto transposeOp = dyn_cast<linalg::TransposeOp>(defOp)) {
    if (wantedSlice) {
      auto mappedSliceOr = mapTransposeOutputToInputSlice(
          *wantedSlice, transposeOp.getPermutation(), defOp);
      if (failed(mappedSliceOr))
        return failure();
      wantedSlice = std::move(*mappedSliceOr);
    }
    layoutOps.push_back(transposeOp);
    return resolveLayoutChains(transposeOp.getInput(), std::move(wantedSlice),
                               semanticOps, std::move(layoutOps),
                               std::move(targetSlice));
  }

  if (auto extractSliceOp = dyn_cast<tensor::ExtractSliceOp>(defOp)) {
    auto extractSliceOr = getStaticSlice(extractSliceOp);
    if (failed(extractSliceOr))
      return failure();

    if (!wantedSlice) {
      auto fullSliceOr = getFullStaticSlice(value);
      if (failed(fullSliceOr))
        return failure();
      wantedSlice = std::move(*fullSliceOr);
    }
    if (!targetSlice)
      targetSlice = *wantedSlice;

    auto composedOr = composeExtractSlice(*extractSliceOr, *wantedSlice, defOp);
    if (failed(composedOr))
      return failure();

    layoutOps.push_back(extractSliceOp);
    return resolveLayoutChains(extractSliceOp.getSource(),
                               std::move(*composedOr), semanticOps,
                               std::move(layoutOps), std::move(targetSlice));
  }

  if (auto insertSliceOp = dyn_cast<tensor::InsertSliceOp>(defOp)) {
    auto insertSliceOr = getStaticSlice(insertSliceOp);
    if (failed(insertSliceOr))
      return failure();

    if (!wantedSlice) {
      auto fullSliceOr = getFullStaticSlice(value);
      if (failed(fullSliceOr))
        return failure();
      wantedSlice = std::move(*fullSliceOr);
    }
    if (!targetSlice)
      targetSlice = *wantedSlice;

    auto intersectionOr = intersectSlices(*wantedSlice, *insertSliceOr, defOp);
    if (failed(intersectionOr))
      return failure();

    layoutOps.push_back(insertSliceOp);
    if (!*intersectionOr)
      return resolveLayoutChains(insertSliceOp.getDest(), *wantedSlice,
                                 semanticOps, std::move(layoutOps),
                                 std::move(targetSlice));

    StaticSlice sourceSlice =
        mapIntoInsertedSource(**intersectionOr, *insertSliceOr);
    StaticSlice sourceTargetSlice =
        mapWantedSubsliceToTarget(**intersectionOr, *wantedSlice, *targetSlice);
    if (slicesEqual(**intersectionOr, *wantedSlice))
      return resolveLayoutChains(
          insertSliceOp.getSource(), std::move(sourceSlice), semanticOps,
          std::move(layoutOps), std::move(sourceTargetSlice));

    SmallVector<LayoutChain, 4> chains;
    SmallVector<Operation *, 4> sourceLayoutOps = layoutOps;
    auto sourceChainsOr = resolveLayoutChains(
        insertSliceOp.getSource(), std::move(sourceSlice), semanticOps,
        std::move(sourceLayoutOps), std::move(sourceTargetSlice));
    if (failed(sourceChainsOr))
      return failure();
    llvm::append_range(chains, std::move(*sourceChainsOr));

    for (StaticSlice destSlice :
         subtractSlice(*wantedSlice, **intersectionOr)) {
      SmallVector<Operation *, 4> destLayoutOps = layoutOps;
      StaticSlice destTargetSlice =
          mapWantedSubsliceToTarget(destSlice, *wantedSlice, *targetSlice);
      auto destChainsOr = resolveLayoutChains(
          insertSliceOp.getDest(), std::move(destSlice), semanticOps,
          std::move(destLayoutOps), std::move(destTargetSlice));
      if (failed(destChainsOr))
        return failure();
      llvm::append_range(chains, std::move(*destChainsOr));
    }
    return chains;
  }

  if (auto expandOp = dyn_cast<tensor::ExpandShapeOp>(defOp)) {
    layoutOps.push_back(expandOp);
    return resolveLayoutChains(expandOp.getSrc(), std::nullopt, semanticOps,
                               std::move(layoutOps), std::move(targetSlice));
  }

  if (auto collapseOp = dyn_cast<tensor::CollapseShapeOp>(defOp)) {
    layoutOps.push_back(collapseOp);
    return resolveLayoutChains(collapseOp.getSrc(), std::nullopt, semanticOps,
                               std::move(layoutOps), std::move(targetSlice));
  }

  return defOp->emitError() << "unsupported layout transform op";
}

template <typename EdgeTy>
static FailureOr<SmallVector<EdgeTy, 4>>
buildEdgesForOperand(Value operand, unsigned consumerNodeId,
                     unsigned consumerOperandId,
                     DenseSet<Operation *> &semanticOps,
                     DenseMap<Operation *, unsigned> &opToNodeId) {
  auto chainsOr = resolveLayoutChains(operand, std::nullopt, semanticOps);
  if (failed(chainsOr))
    return failure();

  SmallVector<EdgeTy, 4> edges;
  for (LayoutChain &chain : *chainsOr) {
    Value source = chain.source;
    EdgeTy edge;
    edge.value = operand;
    edge.consumerNodeId = consumerNodeId;
    edge.consumerOperandId = consumerOperandId;
    if (Operation *defOp = source.getDefiningOp()) {
      if (auto it = opToNodeId.find(defOp); it != opToNodeId.end()) {
        edge.producerNodeId = it->second;
        edge.producerResultId = cast<OpResult>(source).getResultNumber();
        edge.layoutChain = std::move(chain);
        edges.push_back(std::move(edge));
        continue;
      }
    }
    // otherwise source is an external value
    edge.producerNodeId = kNullId;
    edge.producerResultId = kNullId;
    edge.layoutChain = std::move(chain);
    edges.push_back(std::move(edge));
  }
  return edges;
}

FailureOr<ProgramGraph> ProgramGraph::build(func::FuncOp func) {
  ProgramGraph graph;
  graph.func = func;

  Block &entryBlock = func.getBody().front();
  DenseMap<Operation *, unsigned> opToNodeId;
  DenseSet<Operation *> semanticOps;

  // Construct semantic nodes for all primitive semantic ops
  // DenseSet<Operation *> preTrans = findPreTransforms(entryBlock);
  for (Operation &op : entryBlock.without_terminator()) {
    if (!isPrimitiveSemanticOp(&op))
      continue;
    semanticOps.insert(&op);
    opToNodeId[&op] = graph.nodes.size();
    graph.nodes.emplace_back(&op);
  }
  if (graph.nodes.empty())
    return std::move(graph); // no semantic nodes, return empty graph

  // Construct edges by walking operand-def chains
  for (auto [nodeId, node] : llvm::enumerate(graph.nodes)) {
    for (auto [opId, operand] :
         llvm::enumerate(node.identity.op->getOperands())) {
      auto edgesOr = buildEdgesForOperand<ProgramGraphEdge>(
          operand, nodeId, opId, semanticOps, opToNodeId);
      if (failed(edgesOr))
        return failure();
      for (ProgramGraphEdge &edge : *edgesOr) {
        if (!edge.isExternalInput())
          graph.nodes[edge.producerNodeId].outEdgeIds.push_back(
              graph.edges.size());
        node.inEdgeIds.push_back(graph.edges.size());
        graph.edges.push_back(std::move(edge));
      }
    }
  }

  // Construct output external edges
  Operation *terminator = entryBlock.getTerminator();
  for (auto [opId, operand] : llvm::enumerate(terminator->getOperands())) {
    auto edgesOr = buildEdgesForOperand<ProgramGraphEdge>(
        operand, kNullId, opId, semanticOps, opToNodeId);
    if (failed(edgesOr))
      return failure();
    for (ProgramGraphEdge &edge : *edgesOr) {
      if (!edge.isExternalInput())
        graph.nodes[edge.producerNodeId].outEdgeIds.push_back(
            graph.edges.size());
      graph.edges.push_back(std::move(edge));
    }
  }

  return std::move(graph);
}

const ProgramGraphEdge *
ProgramGraph::findEdge(unsigned producerNodeId, unsigned consumerNodeId,
                       unsigned producerResultId,
                       unsigned consumerOperandId) const {
  if (producerNodeId >= nodes.size() || consumerNodeId >= nodes.size())
    return nullptr;
  for (unsigned id : nodes[producerNodeId].outEdgeIds) {
    const auto &edge = edges[id];
    if (edge.consumerNodeId == consumerNodeId &&
        edge.producerResultId == producerResultId &&
        edge.consumerOperandId == consumerOperandId)
      return &edge;
  }
  return nullptr;
}

static void emitDotHeader(llvm::raw_ostream &os, llvm::Twine title) {
  os << "digraph \"" << title << "\" {\n";
  os.indent(2) << "rankdir=LR;\n";
  os.indent(2) << "node [shape=box];\n";
}

static std::string makeNodeId(unsigned id) { return "n" + std::to_string(id); }

static void emitDotNode(llvm::raw_ostream &os, StringRef nodeId,
                        ArrayRef<std::string> labels, StringRef shape = "") {
  os.indent(2) << nodeId << " [";
  if (!shape.empty())
    os << "shape=" << shape << ",";
  os << "label=\"" << llvm::join(labels, "\\l") << "\\l\"];\n";
}

static void emitDotEdge(llvm::raw_ostream &os, StringRef sourceId,
                        StringRef targetId, ArrayRef<std::string> labels) {
  os.indent(2) << sourceId << " -> " << targetId;
  if (!labels.empty())
    os << " [label=\"" << llvm::join(labels, "\\l") << "\\l\"]";
  os << ";\n";
}

static std::string getOperationName(Operation *op) {
  assert(op && "expected non-null operation");
  return op->getName().getStringRef().str();
}

static std::string getOperationKind(Operation *op) {
  std::string name = getOperationName(op);
  size_t dot = name.rfind('.');
  if (dot == std::string::npos)
    return name;
  return name.substr(dot + 1);
}

static std::string formatValue(Value value) {
  std::string str;
  if (auto blockArg = dyn_cast<BlockArgument>(value))
    str = getOperationName(blockArg.getOwner()->getParentOp()) + ":%arg" +
          std::to_string(blockArg.getArgNumber());

  else
    str = getOperationName(value.getDefiningOp()) + ":%" +
          std::to_string(cast<OpResult>(value).getResultNumber());
  return str;
}

static std::string formatPort(StringRef prefix, unsigned id) {
  if (id == kNullId)
    return "ext";
  return (prefix + Twine(id)).str();
}

static std::string formatTransformChain(const LayoutChain &layout) {
  SmallVector<std::string, 4> pieces;
  std::string current;
  unsigned count = 0;

  auto flush = [&]() {
    if (current.empty())
      return;
    if (count == 1)
      pieces.push_back(current);
    else
      pieces.push_back(current + " x" + std::to_string(count));
  };

  for (Operation *op : layout.layoutOps) {
    std::string kind = getOperationKind(op);
    if (kind == current) {
      ++count;
      continue;
    }
    flush();
    current = std::move(kind);
    count = 1;
  }
  flush();

  return llvm::join(pieces, " -> ");
}

static void appendTransformLabel(SmallVectorImpl<std::string> &labels,
                                 const LayoutChain &layout) {
  std::string chain = formatTransformChain(layout);
  if (!chain.empty())
    labels.push_back("via " + chain);
}

static SmallVector<std::string, 2>
makeEdgeLabels(unsigned producerPort, unsigned consumerPort,
               const LayoutChain &layout, StringRef producerPrefix = "r",
               StringRef consumerPrefix = "o") {
  SmallVector<std::string, 2> labels{
      formatPort(producerPrefix, producerPort) + " -> " +
          formatPort(consumerPrefix, consumerPort),
  };
  appendTransformLabel(labels, layout);
  return labels;
}

void ProgramGraph::dump(llvm::raw_ostream &os) const {
  emitDotHeader(os,
                "Program @" + const_cast<func::FuncOp &>(func).getSymName());
  for (auto [id, node] : llvm::enumerate(nodes)) {
    SmallVector<std::string, 2> labels{
        makeNodeId(id),
        getOperationKind(node.identity.op),
    };
    emitDotNode(os, makeNodeId(id), labels);
  }
  for (auto [id, edge] : llvm::enumerate(edges)) {
    std::string sourceId, targetId;
    if (edge.isExternalInput()) {
      sourceId = "extin" + std::to_string(id);
      targetId = makeNodeId(edge.consumerNodeId);
      SmallVector<std::string, 2> labels{
          "in",
          formatValue(edge.layoutChain.source),
      };
      emitDotNode(os, sourceId, labels, "ellipse");
    } else if (edge.isExternalOutput()) {
      sourceId = makeNodeId(edge.producerNodeId);
      targetId = "extout" + std::to_string(id);
      SmallVector<std::string, 2> labels{
          "out",
          formatValue(edge.value),
      };
      emitDotNode(os, targetId, labels, "ellipse");
    } else {
      sourceId = makeNodeId(edge.producerNodeId);
      targetId = makeNodeId(edge.consumerNodeId);
    }
    emitDotEdge(os, sourceId, targetId,
                makeEdgeLabels(edge.producerResultId, edge.consumerOperandId,
                               edge.layoutChain));
  }
  os << "}\n";
}

static unsigned selectAnchorNode(InstructionGraph &graph) {
  assert(!graph.nodes.empty() && "expected non-empty instruction graph");
  unsigned bestIdx = kNullId;
  // TODO: use a better heuristic for anchor node selection
  auto bestKey = std::tuple<unsigned, int>(0, 0); // (numEdges, nodeIdx)
  for (auto [idx, node] : llvm::enumerate(graph.nodes)) {
    unsigned numEdges = node.inEdgeIds.size() + node.outEdgeIds.size();
    auto key = std::tuple<unsigned, int>(numEdges, -static_cast<int>(idx));
    if (key > bestKey) {
      bestKey = key;
      bestIdx = idx;
    }
  }
  assert(bestIdx != kNullId && "expected to find an anchor node");
  return bestIdx;
}

FailureOr<InstructionGraph> InstructionGraph::build(DefineOp defineOp) {
  InstructionGraph graph;
  graph.instruction = defineOp;

  Block &b = defineOp.getSemanticsBlock();
  DenseSet<Operation *> semanticOps;
  DenseMap<Operation *, unsigned> opToNodeId;
  for (Operation &op : b.without_terminator()) {
    if (!isPrimitiveSemanticOp(&op))
      continue;
    semanticOps.insert(&op);
    opToNodeId[&op] = graph.nodes.size();
    graph.nodes.emplace_back(&op);
  }
  if (graph.nodes.empty())
    return std::move(graph); // no semantic nodes, return empty graph

  // Construct edges by walking operand-def chains
  for (auto [nodeId, node] : llvm::enumerate(graph.nodes)) {
    for (auto [opId, operand] :
         llvm::enumerate(node.identity.op->getOperands())) {
      auto edgesOr = buildEdgesForOperand<InstructionGraphEdge>(
          operand, nodeId, opId, semanticOps, opToNodeId);
      if (failed(edgesOr))
        return failure();
      for (InstructionGraphEdge &edge : *edgesOr) {
        if (!edge.isExternalInput())
          graph.nodes[edge.producerNodeId].outEdgeIds.push_back(
              graph.edges.size());
        node.inEdgeIds.push_back(graph.edges.size());
        graph.edges.push_back(std::move(edge));
      }
    }
  }

  Operation *terminator = b.getTerminator();
  for (auto [outputId, operand] : llvm::enumerate(terminator->getOperands())) {
    auto edgesOr = buildEdgesForOperand<InstructionGraphEdge>(
        operand, kNullId, outputId, semanticOps, opToNodeId);
    if (failed(edgesOr))
      return failure();
    for (InstructionGraphEdge &edge : *edgesOr) {
      if (!edge.isExternalInput())
        graph.nodes[edge.producerNodeId].outEdgeIds.push_back(
            graph.edges.size());
      graph.edges.push_back(std::move(edge));
    }
  }

  // select anchor node
  graph.anchorNodeId = selectAnchorNode(graph);
  return std::move(graph);
}

void InstructionGraph::dump(llvm::raw_ostream &os) const {
  emitDotHeader(os, "Instruction @" +
                        const_cast<DefineOp &>(instruction).getSymName());
  for (auto [id, node] : llvm::enumerate(nodes)) {
    SmallVector<std::string, 3> labels{
        makeNodeId(id),
        getOperationKind(node.identity.op),
    };
    if (id == anchorNodeId)
      labels.push_back("anchor");
    emitDotNode(os, makeNodeId(id), labels);
  }
  for (auto [id, edge] : llvm::enumerate(edges)) {
    if (!edge.isExternal()) {
      emitDotEdge(os, makeNodeId(edge.producerNodeId),
                  makeNodeId(edge.consumerNodeId),
                  makeEdgeLabels(edge.producerResultId, edge.consumerOperandId,
                                 edge.layoutChain));
    } else if (edge.isExternalInput()) {
      std::string sourceId = "extin" + std::to_string(id);
      std::string targetId = makeNodeId(edge.consumerNodeId);
      SmallVector<std::string, 2> labels{
          "in",
          formatValue(edge.layoutChain.source),
      };
      emitDotNode(os, sourceId, labels, "ellipse");
      emitDotEdge(
          os, sourceId, targetId,
          makeEdgeLabels(kNullId, edge.consumerOperandId, edge.layoutChain));
    } else if (edge.isExternalOutput()) {
      std::string sourceId = makeNodeId(edge.producerNodeId);
      std::string targetId = "extout" + std::to_string(id);
      SmallVector<std::string, 2> labels{
          "out",
          formatValue(edge.value),
      };
      emitDotNode(os, targetId, labels, "ellipse");
      emitDotEdge(os, sourceId, targetId,
                  makeEdgeLabels(edge.producerResultId, edge.consumerOperandId,
                                 edge.layoutChain, "r", "out"));
    }
  }
  os << "}\n";
}

static llvm::hash_code hashOperation(Operation *op) {
  unsigned nInputs, nOutputs;
  SmallVector<AffineMap> indexingMaps;
  SmallVector<utils::IteratorType> iterators;
  if (auto linalgOp = dyn_cast<linalg::LinalgOp>(op)) {
    nInputs = linalgOp.getNumDpsInputs();
    nOutputs = linalgOp.getNumDpsInits();
    indexingMaps = linalgOp.getIndexingMapsArray();
    iterators = linalgOp.getIteratorTypesArray();
  } else if (auto softmaxOp = dyn_cast<linalg::SoftmaxOp>(op)) {
    nInputs = softmaxOp.getNumDpsInputs();
    nOutputs = softmaxOp.getNumDpsInits();
    iterators = softmaxOp.getLoopIteratorTypes();
  } else {
    nInputs = op->getNumOperands();
    nOutputs = op->getNumResults();
  }
  llvm::hash_code mapHash = llvm::hash_combine_range(indexingMaps);
  llvm::hash_code iterHash = llvm::hash_combine_range(iterators);
  return llvm::hash_combine(getOperationName(op), nInputs, nOutputs, mapHash,
                            iterHash);
}

SemanticIdentity::SemanticIdentity(Operation *op)
    : op(op), opName(getOperationName(op)), hashValue(hashOperation(op)) {
  assert(isPrimitiveSemanticOp(op) && "expected a primitive semantic op");
}

static bool genericBodiesMatch(Block *lhs, Block *rhs) {
  if (lhs->getNumArguments() != rhs->getNumArguments())
    return false;

  llvm::SmallDenseMap<Value, unsigned, 16> lhsIds;
  llvm::SmallDenseMap<Value, unsigned, 16> rhsIds;
  for (auto [idx, arg] : llvm::enumerate(lhs->getArguments()))
    lhsIds[arg] = idx;
  for (auto [idx, arg] : llvm::enumerate(rhs->getArguments()))
    rhsIds[arg] = idx;

  auto lhsIt = lhs->begin();
  auto rhsIt = rhs->begin();
  unsigned nextId = lhs->getNumArguments();
  for (; lhsIt != lhs->end() && rhsIt != rhs->end(); ++lhsIt, ++rhsIt) {
    if (isa<linalg::YieldOp>(*lhsIt) || isa<linalg::YieldOp>(*rhsIt))
      return isa<linalg::YieldOp>(*lhsIt) && isa<linalg::YieldOp>(*rhsIt);

    if (lhsIt->getName() != rhsIt->getName() ||
        lhsIt->getNumOperands() != rhsIt->getNumOperands() ||
        lhsIt->getNumResults() != rhsIt->getNumResults())
      return false;

    for (unsigned i = 0; i < lhsIt->getNumOperands(); ++i) {
      if (lhsIds.lookup(lhsIt->getOperand(i)) !=
          rhsIds.lookup(rhsIt->getOperand(i)))
        return false;
    }

    if (auto lhsConst = dyn_cast<arith::ConstantOp>(&*lhsIt)) {
      auto rhsConst = dyn_cast<arith::ConstantOp>(&*rhsIt);
      if (!rhsConst || lhsConst.getValue() != rhsConst.getValue())
        return false;
    }

    for (auto [lhsResult, rhsResult] :
         llvm::zip(lhsIt->getResults(), rhsIt->getResults())) {
      lhsIds[lhsResult] = nextId;
      rhsIds[rhsResult] = nextId;
      ++nextId;
    }
  }
  return lhsIt == lhs->end() && rhsIt == rhs->end();
}

bool SemanticIdentity::semanticallyMatches(
    const SemanticIdentity &other) const {
  if (hashValue != other.hashValue)
    return false;
  Operation *lhs = op, *rhs = other.op;

  if (lhs->getName() != rhs->getName() ||
      lhs->getNumOperands() != rhs->getNumOperands() ||
      lhs->getNumResults() != rhs->getNumResults())
    return false;

  auto checkValueTypes = [](Value lhs, Value rhs) {
    Type lhsType = lhs.getType();
    Type rhsType = rhs.getType();
    if (lhsType == rhsType)
      return true;
    // only cmp element type and rank, ignore dim sizes
    auto lhsShaped = dyn_cast<ShapedType>(lhsType);
    auto rhsShaped = dyn_cast<ShapedType>(rhsType);
    if (lhsShaped && rhsShaped)
      return lhsShaped.getElementType() == rhsShaped.getElementType() &&
             lhsShaped.getRank() == rhsShaped.getRank();
    return false;
  };

  for (auto [lhsOperand, rhsOperand] :
       llvm::zip(lhs->getOperands(), rhs->getOperands())) {
    if (!checkValueTypes(lhsOperand, rhsOperand))
      return false;
  }
  for (auto [lhsResult, rhsResult] :
       llvm::zip(lhs->getResults(), rhs->getResults())) {
    if (!checkValueTypes(lhsResult, rhsResult))
      return false;
  }

  auto lhsGeneric = dyn_cast<linalg::GenericOp>(lhs);
  auto rhsGeneric = dyn_cast<linalg::GenericOp>(rhs);
  if (lhsGeneric && rhsGeneric) {
    if (lhsGeneric.getIndexingMaps() != rhsGeneric.getIndexingMaps() ||
        lhsGeneric.getIteratorTypes() != rhsGeneric.getIteratorTypes())
      return false;
    return genericBodiesMatch(&lhsGeneric.getRegion().front(),
                              &rhsGeneric.getRegion().front());
  }
  // for non-generic ops in primitive op set,
  // we consider them semantically equivalent if they have the same name and
  // same number of operands/results (for most cases, comparing names is enough)
  return true;
}

FailureOr<InstructionCollection> InstructionCollection::build(ModuleOp module) {
  LLVM_DEBUG(dbgs() << "=== Building Instruction Collection ===\n");
  InstructionCollection collection;
  for (DefineOp defineOp : module.getOps<DefineOp>()) {
    auto graphOr = InstructionGraph::build(defineOp);
    if (failed(graphOr))
      return failure();
    LLVM_DEBUG({
      dbgs() << "Instruction @" << defineOp.getSymName() << ":";
      if (graphOr->nodes.empty())
        dbgs() << " <empty graph>\n";
      else
        dbgs() << "\n", graphOr->dump(dbgs());
    });
    if (graphOr->nodes.empty())
      continue;
    llvm::hash_code hash =
        graphOr->nodes[graphOr->anchorNodeId].identity.hashValue;
    unsigned idx = collection.instructions.size();
    collection.byAnchorHash[hash].push_back(idx);
    collection.instructions.push_back(std::move(*graphOr));
  }
  return std::move(collection);
}

SmallVector<const InstructionGraph *, 2>
InstructionCollection::lookup(SemanticIdentity &anchor) const {
  // fast prune with hash
  auto it = byAnchorHash.find(anchor.hashValue);
  if (it == byAnchorHash.end())
    return {};
  SmallVector<const InstructionGraph *, 2> matches;
  for (unsigned idx : it->second) {
    const auto &graph = instructions[idx];
    if (graph.nodes[graph.anchorNodeId].identity.semanticallyMatches(anchor))
      matches.push_back(&graph);
  }
  return matches;
}

namespace {
struct MatchState {
  const InstructionGraph &pattern;
  ProgramGraph &program;
  // flat mapping between pattern node idx and program node idx
  SmallVector<unsigned, 4> patternToProgramNode;
  SmallVector<unsigned, 4> programToPatternNode;
  SmallVector<bool, 4> mappedPatternNodes;
  SmallVector<bool, 4> mappedProgramNodes;
  MatchState(const InstructionGraph &pattern, ProgramGraph &program)
      : pattern(pattern), program(program),
        patternToProgramNode(pattern.nodes.size(), kNullId),
        programToPatternNode(program.nodes.size(), kNullId),
        mappedPatternNodes(pattern.nodes.size(), false),
        mappedProgramNodes(program.nodes.size(), false) {}
};
} // namespace

static unsigned getNumMappedNeighbors(MatchState &state,
                                      unsigned patternNodeIdx) {
  unsigned count = 0;
  const auto &patternNode = state.pattern.nodes[patternNodeIdx];
  for (unsigned edgeId : patternNode.inEdgeIds) {
    const auto &edge = state.pattern.edges[edgeId];
    if (edge.isExternalInput() || state.mappedPatternNodes[edge.producerNodeId])
      ++count;
  }
  for (unsigned edgeId : patternNode.outEdgeIds) {
    const auto &edge = state.pattern.edges[edgeId];
    if (edge.isExternalOutput() ||
        state.mappedPatternNodes[edge.consumerNodeId])
      ++count;
  }
  return count;
}

static unsigned chooseNextPatternNode(MatchState &state) {
  unsigned bestId = kNullId;
  // TODO: add a better heuristic for pattern node selection
  auto bestKey =
      std::tuple<unsigned, int>(0, 0); // (numMappedNeighbors, nodeIdx)
  for (auto [id, node] : llvm::enumerate(state.pattern.nodes)) {
    if (state.mappedPatternNodes[id])
      continue;
    unsigned numMappedNeighbors = getNumMappedNeighbors(state, id);
    auto key =
        std::tuple<unsigned, int>(numMappedNeighbors, -static_cast<int>(id));
    if (key > bestKey) {
      bestKey = key;
      bestId = id;
    }
  }
  assert(bestId != kNullId && "expected to find a next pattern node");
  return bestId;
}

static bool edgeShapeMatches(const ProgramGraphEdge &patternEdge,
                             const ProgramGraphEdge &sourceEdge) {
  return patternEdge.producerResultId == sourceEdge.producerResultId &&
         patternEdge.consumerOperandId == sourceEdge.consumerOperandId;
  // TODO: compare transform chain
}

/// Verify all edges between the new source node and already-mapped source nodes
/// exactly match the pattern graph. This enforces induced-exact matching.
static bool hasConsistentEdges(MatchState &state, unsigned patternNodeId,
                               unsigned programNodeId) {
  for (unsigned otherPatternId = 0; otherPatternId < state.pattern.nodes.size();
       ++otherPatternId) {
    if (!state.mappedPatternNodes[otherPatternId] ||
        otherPatternId == patternNodeId)
      continue;
    unsigned otherProgramId = state.patternToProgramNode[otherPatternId];

    for (unsigned edgeIdx : state.pattern.nodes[patternNodeId].outEdgeIds) {
      const auto &patternEdge = state.pattern.edges[edgeIdx];
      if (patternEdge.consumerNodeId != otherPatternId)
        continue;
      const auto *programEdge = state.program.findEdge(
          programNodeId, otherProgramId, patternEdge.producerResultId,
          patternEdge.consumerOperandId);
      if (!programEdge || !edgeShapeMatches(patternEdge, *programEdge))
        return false;
    }
    for (unsigned edgeIdx : state.pattern.nodes[patternNodeId].inEdgeIds) {
      const auto &patternEdge = state.pattern.edges[edgeIdx];
      if (patternEdge.producerNodeId != otherPatternId)
        continue;
      const auto *programEdge = state.program.findEdge(
          otherProgramId, programNodeId, patternEdge.producerResultId,
          patternEdge.consumerOperandId);
      if (!programEdge || !edgeShapeMatches(patternEdge, *programEdge))
        return false;
    }

    for (unsigned programEdgeId :
         state.program.nodes[programNodeId].outEdgeIds) {
      const auto &programEdge = state.program.edges[programEdgeId];
      if (programEdge.consumerNodeId != otherProgramId)
        continue;
      bool matched = false;
      for (unsigned patternEdgeIdx :
           state.pattern.nodes[patternNodeId].outEdgeIds) {
        const auto &patternEdge = state.pattern.edges[patternEdgeIdx];
        if (patternEdge.consumerNodeId == otherPatternId &&
            edgeShapeMatches(patternEdge, programEdge)) {
          matched = true;
          break;
        }
      }
      if (!matched)
        return false;
    }
    for (unsigned programEdgeId :
         state.program.nodes[programNodeId].inEdgeIds) {
      const auto &programEdge = state.program.edges[programEdgeId];
      if (programEdge.producerNodeId != otherProgramId)
        continue;
      bool matched = false;
      for (unsigned patternEdgeIdx :
           state.pattern.nodes[patternNodeId].inEdgeIds) {
        const auto &patternEdge = state.pattern.edges[patternEdgeIdx];
        if (patternEdge.producerNodeId == otherPatternId &&
            edgeShapeMatches(patternEdge, programEdge)) {
          matched = true;
          break;
        }
      }
      if (!matched)
        return false;
    }
  }
  return true;
}

static SmallVector<unsigned, 4>
collectCandidateProgramNodes(MatchState &state, unsigned patternNodeIdx) {
  SmallVector<unsigned, 4> candidates;
  const auto &patternNode = state.pattern.nodes[patternNodeIdx];
  for (unsigned programNodeId = 0; programNodeId < state.program.nodes.size();
       ++programNodeId) {
    if (state.mappedProgramNodes[programNodeId])
      continue;
    const auto &programNode = state.program.nodes[programNodeId];
    if (!patternNode.identity.semanticallyMatches(programNode.identity))
      continue;
    if (!hasConsistentEdges(state, patternNodeIdx, programNodeId))
      continue;
    candidates.push_back(programNodeId);
  }

  // TODO: maybe a better heuristic for candidate ordering
  llvm::sort(candidates, [&](unsigned lhsId, unsigned rhsId) {
    const auto &lhsNode = state.program.nodes[lhsId];
    const auto &rhsNode = state.program.nodes[rhsId];
    auto lhsKey = std::tuple<unsigned, int>(lhsNode.inEdgeIds.size() +
                                                lhsNode.outEdgeIds.size(),
                                            -static_cast<int>(lhsId));
    auto rhsKey = std::tuple<unsigned, int>(rhsNode.inEdgeIds.size() +
                                                rhsNode.outEdgeIds.size(),
                                            -static_cast<int>(rhsId));
    return lhsKey > rhsKey;
  });

  return candidates;
}

static MatchCandidate buildMatchCandidate(MatchState &state,
                                          unsigned programAnchorNodeId) {
  MatchCandidate candidate;
  candidate.instruction = &state.pattern;
  candidate.programAnchorNodeId = programAnchorNodeId;
  for (unsigned patternNodeId = 0; patternNodeId < state.pattern.nodes.size();
       ++patternNodeId) {
    unsigned programNodeId = state.patternToProgramNode[patternNodeId];
    SemanticIdentity identity = state.program.nodes[programNodeId].identity;
    candidate.sourceOps.push_back(identity);
    candidate.patternToProgramNodeId.push_back(programNodeId);
  }
  return candidate;
}

static void collectMatchesForAnchor(MatchState &state,
                                    unsigned programAnchorNodeIdx,
                                    MatchCandidates &results) {
  if (llvm::all_of(state.mappedPatternNodes,
                   [](bool mapped) { return mapped; })) {
    LLVM_DEBUG({
      dbgs() << "anchor[" << programAnchorNodeIdx << "]: "
             << state.program.nodes[programAnchorNodeIdx].identity.op->getName()
             << " -> @"
             << const_cast<DefineOp &>(state.pattern.instruction).getSymName()
             << "\n";
    });
    results.push_back(buildMatchCandidate(state, programAnchorNodeIdx));
    return;
  }
  unsigned nextPatternNodeIdx = chooseNextPatternNode(state);
  auto candidates = collectCandidateProgramNodes(state, nextPatternNodeIdx);
  for (unsigned programNodeIdx : candidates) {
    // update state with new mapping
    state.patternToProgramNode[nextPatternNodeIdx] = programNodeIdx;
    state.programToPatternNode[programNodeIdx] = nextPatternNodeIdx;
    state.mappedPatternNodes[nextPatternNodeIdx] = true;
    state.mappedProgramNodes[programNodeIdx] = true;
    auto cleanup = llvm::scope_exit([&] {
      state.patternToProgramNode[nextPatternNodeIdx] = kNullId;
      state.programToPatternNode[programNodeIdx] = kNullId;
      state.mappedPatternNodes[nextPatternNodeIdx] = false;
      state.mappedProgramNodes[programNodeIdx] = false;
    });
    collectMatchesForAnchor(state, programAnchorNodeIdx, results);
  }
}

static MatchCandidates collectMatchesForAnchor(const InstructionGraph &pattern,
                                               ProgramGraph &program,
                                               unsigned sourceNodeIdx) {
  MatchCandidates candidates;
  MatchState state(pattern, program);
  // initialize state with anchor node mapping
  state.patternToProgramNode[pattern.anchorNodeId] = sourceNodeIdx;
  state.programToPatternNode[sourceNodeIdx] = pattern.anchorNodeId;
  state.mappedPatternNodes[pattern.anchorNodeId] = true;
  state.mappedProgramNodes[sourceNodeIdx] = true;
  collectMatchesForAnchor(state, sourceNodeIdx, candidates);
  return candidates;
}

static MatchCandidates
collectInstructionMatches(ProgramGraph &program,
                          InstructionCollection &collection) {
  MatchCandidates candidates;
  for (auto [idx, sourceNode] : llvm::enumerate(program.nodes)) {
    // Perform a selection-dag like matching algorithm
    // use hash
    auto patterns = collection.lookup(sourceNode.identity);
    for (const InstructionGraph *pattern : patterns) {
      auto matches = collectMatchesForAnchor(*pattern, program, idx);
      llvm::append_range(candidates, std::move(matches));
    }
  }
  return candidates;
}

static DefineOp getInstruction(const InstructionGraph &graph) {
  return const_cast<DefineOp &>(graph.instruction);
}

static std::optional<unsigned>
getExternalInputAccessOperandIdx(const InstructionGraph &pattern,
                                 const InstructionGraphEdge &edge) {
  Block &computeBlock = getInstruction(pattern).getSemanticsBlock();
  auto arg = dyn_cast<BlockArgument>(edge.layoutChain.source);
  if (!arg || arg.getOwner() != &computeBlock)
    return std::nullopt;
  return arg.getArgNumber();
}

static FailureOr<const InstructionGraphEdge *>
findPatternExternalInputEdge(const InstructionGraph &pattern,
                             unsigned patternNodeId,
                             unsigned patternOperandId) {
  assert(patternNodeId < pattern.nodes.size() && "expected valid pattern node");

  const InstructionGraphEdge *found = nullptr;
  for (unsigned edgeId : pattern.nodes[patternNodeId].inEdgeIds) {
    const InstructionGraphEdge &edge = pattern.edges[edgeId];
    if (!edge.isExternalInput() || edge.consumerOperandId != patternOperandId)
      continue;
    if (found)
      return getInstruction(pattern).emitError()
             << "multiple external input edges for pattern operand";
    found = &edge;
  }
  if (!found)
    return getInstruction(pattern).emitError()
           << "missing external input edge for pattern operand";
  return found;
}

static FailureOr<const InstructionGraphEdge *>
findPatternExternalOutputEdge(const InstructionGraph &pattern,
                              unsigned patternNodeId,
                              unsigned patternResultId) {
  assert(patternNodeId < pattern.nodes.size() && "expected valid pattern node");

  const InstructionGraphEdge *found = nullptr;
  for (unsigned edgeId : pattern.nodes[patternNodeId].outEdgeIds) {
    const InstructionGraphEdge &edge = pattern.edges[edgeId];
    if (!edge.isExternalOutput() || edge.producerResultId != patternResultId)
      continue;
    if (found)
      return getInstruction(pattern).emitError()
             << "multiple external output edges for pattern result";
    found = &edge;
  }
  if (!found)
    return getInstruction(pattern).emitError()
           << "missing external output edge for pattern result";
  return found;
}

static LogicalResult addInputBinding(SemanticGraph &graph,
                                     const ProgramGraphEdge &programEdge,
                                     unsigned producerSemanticNodeId,
                                     unsigned producerPatternNodeId,
                                     unsigned consumerSemanticNodeId,
                                     unsigned consumerPatternNodeId) {
  assert(consumerSemanticNodeId != kNullId && "expected consumer node");
  SemanticGraphNode &node = graph.nodes[consumerSemanticNodeId];

  auto patternEdge = findPatternExternalInputEdge(
      node.pattern, consumerPatternNodeId, programEdge.consumerOperandId);
  if (failed(patternEdge))
    return failure();

  auto accessOperandIdx =
      getExternalInputAccessOperandIdx(node.pattern, **patternEdge);
  if (!accessOperandIdx)
    return success();

  SemanticInputBinding binding;
  binding.accessOperandIdx = *accessOperandIdx;
  binding.patternNodeId = consumerPatternNodeId;
  binding.patternOperandId = programEdge.consumerOperandId;
  binding.sourceNodeId = producerSemanticNodeId;
  binding.sourcePatternNodeId = producerPatternNodeId;
  binding.sourceResultId = programEdge.producerResultId;
  binding.value = programEdge.value;
  binding.layout = programEdge.layoutChain;
  node.inputBindings.push_back(std::move(binding));
  return success();
}

static LogicalResult addOutputBinding(SemanticGraph &graph,
                                      const ProgramGraphEdge &programEdge,
                                      unsigned producerSemanticNodeId,
                                      unsigned producerPatternNodeId,
                                      unsigned consumerSemanticNodeId,
                                      unsigned consumerPatternNodeId) {
  assert(producerSemanticNodeId != kNullId && "expected producer node");
  SemanticGraphNode &node = graph.nodes[producerSemanticNodeId];

  auto patternEdge = findPatternExternalOutputEdge(
      node.pattern, producerPatternNodeId, programEdge.producerResultId);
  if (failed(patternEdge))
    return failure();

  DefineOp defineOp = getInstruction(node.pattern);
  unsigned outputIdx = (*patternEdge)->consumerOperandId;
  unsigned numSources = defineOp.getSources().size();
  unsigned numDestinations = defineOp.getDestinations().size();
  if (outputIdx >= numDestinations)
    return defineOp.emitError()
           << "external output edge exceeds destination buffer count";

  SemanticOutputBinding binding;
  binding.outputIdx = outputIdx;
  binding.accessOperandIdx = numSources + outputIdx;
  binding.patternNodeId = producerPatternNodeId;
  binding.patternResultId = programEdge.producerResultId;
  binding.consumerNodeId = consumerSemanticNodeId;
  binding.consumerPatternNodeId = consumerPatternNodeId;
  binding.consumerOperandId = programEdge.consumerOperandId;
  binding.value = programEdge.value;
  binding.layout = programEdge.layoutChain;
  node.outputBindings.push_back(std::move(binding));
  return success();
}

static FailureOr<SemanticGraph>
buildSemanticGraph(ProgramGraph &program, MatchCandidates &candidates) {
  // TODO: add a sort to prioritize better matches

  DenseSet<Operation *> coveredOps;
  SmallVector<MatchCandidate *, 8> selected;
  for (auto &candidate : candidates) {
    if (llvm::any_of(candidate.sourceOps, [&](SemanticIdentity &identity) {
          return coveredOps.contains(identity.op);
        }))
      continue;
    for (SemanticIdentity &identity : candidate.sourceOps)
      coveredOps.insert(identity.op);
    selected.push_back(&candidate);
  }

  {
    // Check if all semantic ops are covered by the selected candidates
    Operation *failedOp = nullptr;
    auto walkResult = program.func.walk([&](Operation *op) {
      if (isPrimitiveSemanticOp(op) && !coveredOps.contains(op)) {
        failedOp = op;
        return WalkResult::interrupt();
      }
      return WalkResult::advance();
    });
    if (walkResult.wasInterrupted()) {
      return failedOp->emitError() << "failed to find a match for this "
                                      "semantic op in semantic matching";
    }
  }

  llvm::sort(selected, [&](MatchCandidate *lhs, MatchCandidate *rhs) {
    auto *lhsKey = llvm::min_element(lhs->patternToProgramNodeId);
    auto *rhsKey = llvm::min_element(rhs->patternToProgramNodeId);
    return *lhsKey < *rhsKey;
  });

  SemanticGraph graph;
  graph.func = program.func;
  SmallVector<unsigned, 8> programToSemanticNodeId(program.nodes.size(),
                                                   kNullId);
  SmallVector<unsigned, 8> programToPatternNodeId(program.nodes.size(),
                                                  kNullId);

  // Make graph nodes for all selected candidates
  for (auto [semanticNodeId, candidate] : llvm::enumerate(selected)) {
    unsigned semanticId = static_cast<unsigned>(semanticNodeId);
    SemanticGraphNode node(*candidate->instruction);
    node.sourceOps = std::move(candidate->sourceOps);
    node.anchorNodeId = candidate->programAnchorNodeId;
    graph.nodes.push_back(std::move(node));

    for (auto [patternNodeId, programNodeId] :
         llvm::enumerate(candidate->patternToProgramNodeId)) {
      unsigned patternId = static_cast<unsigned>(patternNodeId);
      assert(programNodeId < programToSemanticNodeId.size() &&
             "expected valid program node id");
      assert(programToSemanticNodeId[programNodeId] == kNullId &&
             "selected candidates must not overlap");
      programToSemanticNodeId[programNodeId] = semanticId;
      programToPatternNodeId[programNodeId] = patternId;
    }
  }

  // Construct edges
  for (const ProgramGraphEdge &programEdge : program.edges) {
    unsigned producerSemanticNodeId = kNullId;
    unsigned producerPatternNodeId = kNullId;
    if (!programEdge.isExternalInput()) {
      producerSemanticNodeId =
          programToSemanticNodeId[programEdge.producerNodeId];
      producerPatternNodeId =
          programToPatternNodeId[programEdge.producerNodeId];
    }

    unsigned consumerSemanticNodeId = kNullId;
    unsigned consumerPatternNodeId = kNullId;
    if (!programEdge.isExternalOutput()) {
      consumerSemanticNodeId =
          programToSemanticNodeId[programEdge.consumerNodeId];
      consumerPatternNodeId =
          programToPatternNodeId[programEdge.consumerNodeId];
    }

    // Edges inside a selected multi-op match are represented by the matched
    // instruction pattern and should not become inter-instruction dependencies.
    if (producerSemanticNodeId != kNullId &&
        producerSemanticNodeId == consumerSemanticNodeId)
      continue;

    if (producerSemanticNodeId == kNullId && consumerSemanticNodeId == kNullId)
      continue;

    if (producerSemanticNodeId != kNullId &&
        failed(addOutputBinding(graph, programEdge, producerSemanticNodeId,
                                producerPatternNodeId, consumerSemanticNodeId,
                                consumerPatternNodeId)))
      return failure();
    if (consumerSemanticNodeId != kNullId &&
        failed(addInputBinding(graph, programEdge, producerSemanticNodeId,
                               producerPatternNodeId, consumerSemanticNodeId,
                               consumerPatternNodeId)))
      return failure();

    SemanticGraphEdge edge;
    edge.producerNodeId = producerSemanticNodeId;
    edge.consumerNodeId = consumerSemanticNodeId;
    edge.producerResultId = programEdge.producerResultId;
    edge.consumerOperandId = programEdge.consumerOperandId;
    edge.producerPatternNodeId = producerPatternNodeId;
    edge.consumerPatternNodeId = consumerPatternNodeId;
    edge.transforms = programEdge.layoutChain;

    unsigned edgeId = graph.edges.size();
    if (producerSemanticNodeId != kNullId)
      graph.nodes[producerSemanticNodeId].outEdgeIds.push_back(edgeId);
    if (consumerSemanticNodeId != kNullId)
      graph.nodes[consumerSemanticNodeId].inEdgeIds.push_back(edgeId);
    graph.edges.push_back(std::move(edge));
  }

  return graph;
}

static std::string formatAccess(unsigned idx) {
  return "a" + std::to_string(idx);
}

static std::string formatBoundaryValue(Value value, const LayoutChain &layout) {
  Value display = layout.source ? layout.source : value;
  assert(display && "expected boundary value");
  return formatValue(display);
}

static const SemanticInputBinding *
findInputBindingForEdge(const SemanticGraph &graph,
                        const SemanticGraphEdge &edge) {
  if (edge.consumerNodeId == kNullId)
    return nullptr;

  const SemanticGraphNode &node = graph.nodes[edge.consumerNodeId];
  for (const SemanticInputBinding &binding : node.inputBindings) {
    if (binding.sourceNodeId == edge.producerNodeId &&
        binding.sourcePatternNodeId == edge.producerPatternNodeId &&
        binding.sourceResultId == edge.producerResultId &&
        binding.patternNodeId == edge.consumerPatternNodeId &&
        binding.patternOperandId == edge.consumerOperandId)
      return &binding;
  }
  return nullptr;
}

static const SemanticOutputBinding *
findOutputBindingForEdge(const SemanticGraph &graph,
                         const SemanticGraphEdge &edge) {
  if (edge.producerNodeId == kNullId)
    return nullptr;

  const SemanticGraphNode &node = graph.nodes[edge.producerNodeId];
  for (const SemanticOutputBinding &binding : node.outputBindings) {
    if (binding.patternNodeId == edge.producerPatternNodeId &&
        binding.patternResultId == edge.producerResultId &&
        binding.consumerNodeId == edge.consumerNodeId &&
        binding.consumerPatternNodeId == edge.consumerPatternNodeId &&
        binding.consumerOperandId == edge.consumerOperandId)
      return &binding;
  }
  return nullptr;
}

static SmallVector<std::string, 2>
makeSemanticEdgeLabels(const SemanticGraph &graph,
                       const SemanticGraphEdge &edge) {
  const SemanticOutputBinding *output = findOutputBindingForEdge(graph, edge);
  const SemanticInputBinding *input = findInputBindingForEdge(graph, edge);

  unsigned producerPort =
      output ? output->accessOperandIdx : edge.producerResultId;
  unsigned consumerPort =
      input ? input->accessOperandIdx : edge.consumerOperandId;
  StringRef producerPrefix = output ? "a" : "r";
  StringRef consumerPrefix = input ? "a" : "o";
  return makeEdgeLabels(producerPort, consumerPort, edge.transforms,
                        producerPrefix, consumerPrefix);
}

void SemanticGraph::dump(llvm::raw_ostream &os) const {
  emitDotHeader(os, "Semantic Graph @" +
                        const_cast<func::FuncOp &>(func).getSymName());
  for (auto [id, node] : llvm::enumerate(nodes)) {
    SmallVector<std::string, 2> labels{
        makeNodeId(id),
        "@" + getInstruction(node.pattern).getSymName().str(),
    };
    emitDotNode(os, makeNodeId(id), labels);
  }

  for (const SemanticGraphEdge &edge : edges) {
    if (edge.producerNodeId == kNullId || edge.consumerNodeId == kNullId)
      continue;
    emitDotEdge(os, makeNodeId(edge.producerNodeId),
                makeNodeId(edge.consumerNodeId),
                makeSemanticEdgeLabels(*this, edge));
  }

  for (auto [nodeId, node] : llvm::enumerate(nodes)) {
    for (auto [bindingId, binding] : llvm::enumerate(node.inputBindings)) {
      if (binding.sourceNodeId != kNullId)
        continue;

      std::string sourceId =
          "extin" + std::to_string(nodeId) + "_" + std::to_string(bindingId);
      SmallVector<std::string, 2> labels{
          "in " + formatAccess(binding.accessOperandIdx),
          formatBoundaryValue(binding.value, binding.layout),
      };
      emitDotNode(os, sourceId, labels, "ellipse");
      emitDotEdge(os, sourceId, makeNodeId(nodeId),
                  makeEdgeLabels(kNullId, binding.accessOperandIdx,
                                 binding.layout, "a", "a"));
    }

    for (auto [bindingId, binding] : llvm::enumerate(node.outputBindings)) {
      if (binding.consumerNodeId != kNullId)
        continue;

      std::string targetId =
          "extout" + std::to_string(nodeId) + "_" + std::to_string(bindingId);
      SmallVector<std::string, 2> labels{
          "out " + formatAccess(binding.accessOperandIdx),
          formatBoundaryValue(binding.value, binding.layout),
      };
      emitDotNode(os, targetId, labels, "ellipse");
      emitDotEdge(os, makeNodeId(nodeId), targetId,
                  makeEdgeLabels(binding.accessOperandIdx, kNullId,
                                 binding.layout, "a", "a"));
    }
  }
  os << "}\n";
}

FailureOr<SemanticGraph>
act::runSemanticMatching(func::FuncOp func, InstructionCollection &collection) {
  LLVM_DEBUG(dbgs() << "=== Semantic Matching for function @"
                    << func.getSymName() << " ===\n");
  auto programGraphOr = ProgramGraph::build(func);
  if (failed(programGraphOr))
    return func.emitError()
           << "failed to build program graph for semantic matching";
  LLVM_DEBUG({
    dbgs() << "-------------------\n";
    dbgs() << "Program graph dump:\n";
    dbgs() << "-------------------\n";
  });
  LLVM_DEBUG(programGraphOr->dump(dbgs()));
  LLVM_DEBUG({
    dbgs() << "--------------------\n";
    dbgs() << "Instruction matches:\n";
    dbgs() << "--------------------\n";
  });
  auto candidates = collectInstructionMatches(*programGraphOr, collection);
  auto semanticGraphOr = buildSemanticGraph(*programGraphOr, candidates);
  if (failed(semanticGraphOr))
    return func.emitError() << "cannot find a complete covering of semantic "
                               "patterns for this function";
  LLVM_DEBUG({
    dbgs() << "--------------------\n";
    dbgs() << "Semantic graph dump:\n";
    dbgs() << "--------------------\n";
  });
  LLVM_DEBUG(semanticGraphOr->dump(dbgs()));
  return std::move(semanticGraphOr);
}
