# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Typing stubs for the lazy schedule frontend."""
from typing import Any, Generic, Literal, ParamSpec, TypeAlias, TypeVar, overload

from ..backend.cpu import CPU
from ..backend.vitis.core import Vitis

P = ParamSpec("P")
R = TypeVar("R")

# Native handles / unstubbed query types are surfaced as ``Any``.
Module: TypeAlias = Any
Targets: TypeAlias = Any
SingleTarget: TypeAlias = Any

class Schedule(Generic[P, R]):
    # partition kinds
    Complete: int
    Block: int
    Cyclic: int

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def from_module(cls, module: Module, context: Any = ...) -> Schedule[Any, Any]: ...
    @classmethod
    def from_string(cls, text: str) -> Schedule[Any, Any]: ...
    @classmethod
    def from_file(cls, path: str) -> Schedule[Any, Any]: ...

    # --- export to backend (typed by backend literal) -------------------
    @overload
    def export(self, backend: Literal["vitis"], **kwargs: Any) -> Vitis[P, R]: ...
    @overload
    def export(self, backend: Literal["cpu"], **kwargs: Any) -> CPU[P, R]: ...
    def export_cpu(self, **kwargs: Any) -> CPU[P, R]: ...
    def export_vitis(self, **kwargs: Any) -> Vitis[P, R]: ...

    # --- gated real-IR access -------------------------------------------
    @property
    def payload(self) -> Module: ...
    @property
    def snapshot(self) -> Any: ...

    # --- chainable transforms (return self for fluent pipelines) --------
    def cse(self, targets: Targets = ...) -> Schedule[P, R]: ...
    def dce(self, targets: Targets = ...) -> Schedule[P, R]: ...
    def licm(self, targets: Targets = ...) -> Schedule[P, R]: ...
    def canonicalize(self, targets: Targets = ...) -> Schedule[P, R]: ...
    def pipeline(self, targets: Targets = ..., *, ii: int = ...) -> Schedule[P, R]: ...
    def unroll(self, *args: Any, **kwargs: Any) -> Schedule[P, R]: ...
    def partition(self, *args: Any, **kwargs: Any) -> Schedule[P, R]: ...
    def apply(self) -> Schedule[P, R]: ...
    def compose(
        self, *callees: Schedule[Any, Any], id: Any = ...
    ) -> Schedule[P, R]: ...
    def cleanup_schedule_ids(self) -> Schedule[P, R]: ...
    def debug_dump(self, *, include_values: bool = ...) -> Schedule[P, R]: ...

    # --- introspection --------------------------------------------------
    def format_tree(self, *, include_values: bool = ...) -> str: ...
    def dump_tree(self, *, include_values: bool = ...) -> str: ...
    def dump_transform_script(self) -> str: ...

    # Handle/query primitives (op/loop/buffer/split/tile/reorder/...) return
    # schedule refs that are not modelled here; keep the surface permissive
    # instead of enumerating every transform and its ref type.
    def __getattr__(self, name: str) -> Any: ...
