# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Typing stubs for the Vitis HLS backend."""
from pathlib import Path
from typing import Any, Generic, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

class VitisSynthReport:
    @property
    def xml_path(self) -> Path: ...
    def __getattr__(self, name: str) -> Any: ...

class Vitis(Generic[P, R]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R: ...
    @property
    def hls_code(self) -> str: ...
    def synth(self, *, exist_ok: bool = ...) -> VitisSynthReport: ...

def is_vitis_available() -> bool: ...
